### ISSUE TITLE
請教save_path的路徑

### ISSUE THREAD

**Issue by tsinit2001** [tangyoha/telegram_media_downloader_bak#22]
目前我只會寫成
save_path: E:\TG
效果爲所有文件，不分類存儲到一起了。
請問，能提供個模板，怎麼分類儲存麼？

**Comment by tangyoha** [comment]
@tsinit2001 你好，下面我将用几个实例解释存储路径。

### 1. `chat_title` + `media_datetime`
```yaml
save_path: E:\TG
file_path_prefix:
- chat_title
- media_datetime
```
视频保存完整路径为：E:\TG\\`chat_title` \\`media_datetime`\xxx.mp4
图片保存完整路径为：E:\TG\\`chat_title` \\`media_datetime`\xxx.jpg
### 2. `chat_title` + `media_datetime` + `media_type`
```yaml
save_path: E:\TG
file_path_prefix:
- chat_title
- media_datetime
- media_type
```
视频保存完整路径为：E:\TG\\`chat_title` \\`media_datetime`\\`video `\xxx.mp4
图片保存完整逻辑为：E:\TG\\`chat_title` \\`media_datetime`\\`photo`\xxx.jpg
### 2. `chat_title` + `media_type`
```yaml
save_path: E:\TG
file_path_prefix:
- chat_title
- media_type
```
视频保存完整路径为：E:\TG\\`chat_title`\\`video`\xxx.mp4
图片保存完整逻辑为：E:\TG\\`chat_title`\\`photo`\xxx.jpg
